### ISSUE TITLE
A certain PDF from Archive.org does not display all of its contents on Mac OS

### ISSUE THREAD

**Issue by EngineersNeedArt** [internetarchive/archive-pdf-tools#66]
This PDF:

https://archive.org/download/htewypc/EntertainPocketCalculator.pdf

Tried Preview, Acrobat Reader — all on Mac OS Monterey (an M1 MacBook Pro FWIW).

**Comment by MerlijnWajer** [comment]
Thank you for the report.

I looked at this briefly today with a colleague and we didn't quite figure out why Preview doesn't like it. We also found that iOS PDF rendering has the same issues with this PDF.

I'll try to create a few different versions of the PDF and see if they show the same problems (using CCITT instead of JBIG2 for example). All the PDFs we generate are validated against PDF/A using veraPDF, and I don't think the JBIG2 or JPEG2000 bitstreams are wrong, so I'm a bit puzzled. I'll try to get back to you soon.

**Comment by MerlijnWajer** [comment]
@jrochkind and @EngineersNeedArt - I've created various PDFs from the item in question, I was hoping one of you would be able to try various PDFs on your PDF viewers and let me know which ones work, and which ones don't - they might not all look the same, but that doesn't matter for the purpose of this test (I hope). Testing the files would be very valuable in the blind-debugging process required with Apple Preview. The files in questions are:

1. `normal-jbig2.pdf`
2. `normal-ccitt.pdf`
3. `grok-jbig2.pdf`
4. `grok-ccitt.pdf`
5. `jpeg-ccitt.pdf`

You can find them here: https://archive.org/~merlijn/preview-debugging/

Thanks in advance.

**Comment by EngineersNeedArt** [comment]
The only one that displays the missing content is "jpeg-ccitt.pdf".

The pages (save the first page) however need a white background drawn first to look correct.
<img width="1548" alt="Screen Shot 2023-05-16 at 9 24 05 AM" src="https://github.com/internetarchive/archive-pdf-tools/assets/84056606/861f1549-3f2d-4e15-a3f5-bd225b0d9476">

**Comment by EngineersNeedArt** [comment]
It would be interesting though to iterate on jbig2 a little more to see if there was a way to get it to work.

**Comment by MerlijnWajer** [comment]
Thanks for testing - this indeed seems to suggest to me that the problem seems to be in the usage of JPEG2000 images. To clarify, the `normal` and `grok` files are both using JPEG2000 as foreground and background image encoding, while the `jbig2` and `ccitt` part of it is just the 1-bit mask encoding.

I am aware of the JPEG visual artifacts - I only added it recently to experiment with it, it's not usable in any production setting currently.

I guess next up would be for me to extract the JPEG2000 images from the PDFs, and confirm with you (or a colleague) that Preview also cannot open some of the JPEG2000 images that are embedded in the PDF.

Could you share with me how you get to these console logs, so that I can also do some digging?

**Comment by MerlijnWajer** [comment]
Regarding this part of your comment:

>So it looks like there is an issue with JP2 on Mac OS. I downloaded the "SINGLE PAGE PROCESSED JP2 ZIP" for the same book and only two of the images opened successfully in Apple's Preview. The rest were met with an error dialog suggesting that the file was damaged.

The "SINGLE PAGE PROCESSED JP2 ZIP" files aren't what is in the PDFs - those are further compressed JPEG2000s, but it's good to know that even the "SINGLE PAGE PROCESSED JP2 ZIP" files do not work for you.

**Comment by MerlijnWajer** [comment]
Just to be clear, seeing just a white and black rectangle in this case is entirely expected, thanks for confirming that indeed the JPEG2000s themselves, outside of the PDF, do not open. That seems to be in line with what @jrochkind just posted.

**Comment by EngineersNeedArt** [comment]
> Chrome seems to have no trouble displaying all pages in the original PDF.

Perhaps they have their own "JPEG2KLib" and are not using the OS'es.

**Comment by jrochkind** [comment]
Just a random hypothesis that may have nothing to do with anything, but as part of exploring this domain I have been looking into the complexity on embedded ICC color profiles, and discovering that there is some complexity and disagreement between tools about whether and what kinds of embedded ICC color profiles are supported by jp2k.  

I am curious to see if/what kind of color profile may be embedded in these images.  But I haven't yet figured out how to check that. [This tool](https://jpylyzer.openpreservation.org/) may do so, but does not offer packages for mac!

This is probably a red herring though.

**Comment by EngineersNeedArt** [comment]
Decided to look at the XMP metadata using exiftool for the only known good JP2K image in the bunch (the cover image) and page 5 (known bad image).

```
calhoun@Johns-M1 GliderVintage % exiftool -xmp:all /Users/calhoun/Downloads/EntertainPocketCalculator_jp2/EntertainPocketCalculator_0000.jp2 
XMP Toolkit                     : Image::ExifTool 11.88
Bits Per Sample                 : 8
Photometric Interpretation      : RGB Palette
Planar Configuration            : Chunky
Samples Per Pixel               : 1

calhoun@Johns-M1 GliderVintage % exiftool -xmp:all /Users/calhoun/Downloads/EntertainPocketCalculator_jp2/EntertainPocketCalculator_0005.jp2 
XMP Toolkit                     : Image::ExifTool 11.88
Bits Per Sample                 : 1
Photometric Interpretation      : WhiteIsZero
Planar Configuration            : Chunky
Samples Per Pixel               : 1
calhoun@Johns-M1 GliderVintage % 

```
My small sample-size test suggests 1-bit-per-sample images may be a problem?

**Comment by MerlijnWajer** [comment]
If that is the case, that would be quite disastrous, but I am inclined to agree that this currently seems like a good assumption.

**Comment by MerlijnWajer** [comment]
>No way to generate 8-bit JPEG2K files? Or does the file size become needlessly too large?

I will have to investigate.

In general, for this specific PDF, there is a much better way to handle this, which is to not do the MRC at all, and make the page only a single JBIG2 image, because we can realistically omit the MRC part alltogether for monotone images. I just have not gotten round to implementing that (a heuristic based on the image). I will look later today to see what I can do about 8 bit JPEG2000 images from monotone input, but it feels like a bit of a kludge regardless.

Once we've confirmed this really is the problem, I wonder if there is a way to get Apple to fix Preview.

**Comment by EngineersNeedArt** [comment]
Yeah, Apple should have a Radar filed with a few JPEG2000 images attached that show the issue.

**Comment by EngineersNeedArt** [comment]
Ha ha, no problem. And I'll reach out to some of the engineers I know within Apple about the JPEG2000 bug.

**Comment by MerlijnWajer** [comment]
Oh, if you could reach out that would be great!

If I remember, your also wrote on HN that Adobe had similar problems with some of the pages ("Weirdly, Adobe Reader didn't like it either...."). If you're up for it, I'd like to try to figure out if the problem with Adobe is of a similar nature...

If it is, that will probably sway archive.org to change the software to either always make 8bit images in the PDFs, or for me to just write the code to skip MRC altogether if we have 1bit input images.

**Comment by EngineersNeedArt** [comment]
I would suspect Adobe on Mac OS is using ImageIO for its JPEG2K rendering.

**Comment by EngineersNeedArt** [comment]
I filed a report with Apple and they are looking into the problem with JPEG2000s on their end.
